In [1]:
import numpy as np
import pandas as pd
import random as rd
from random import randint

In [2]:
item_number = np.arange(1,11)
 
weight = (5,7,9,4,1,6,2,8,3,10)
priority_value = (70,10,100,40,50,90,20,80,60,30)
 
print('The list is as follows:')
print('Item No. weight priority value')
for i in range(item_number.shape[0]):
    print('{0}     {1}     {2}\n'.format(item_number[i], weight[i], priority_value[i]))
 
 
print("Enter desired number of chromosomes : ")
number_chromosome = int(input())
print("\n\n")
pop_number = (number_chromosome, item_number.shape[0])
print('population number = {}'.format(pop_number))
print("\n\n")
initial_population = np.random.randint(2, size = pop_number)
initial_population = initial_population.astype(int)
print("Enter Maximum Number of Generations Desired : ")
num_generations = int(input())
print("\n\n")
 
print("Enter the maximum number of items that can be carried: ")
max_item = int(input())
print("\n\n")
 
print("Enter Crossover Rate : ")
pc_value = float(input())
print(" \n\n")
 
print("Enter Mutation Rate : ")
pm_value = float(input())
print("\n\n")
 
print('Initial population: \n{}'.format(initial_population))

The list is as follows:
Item No. weight priority value
1     5     70

2     7     10

3     9     100

4     4     40

5     1     50

6     6     90

7     2     20

8     8     80

9     3     60

10     10     30

Enter desired number of chromosomes : 
6



population number = (6, 10)



Enter Maximum Number of Generations Desired : 
10



Enter the maximum number of items that can be carried: 
35



Enter Crossover Rate : 
0.5
 


Enter Mutation Rate : 
0.4



Initial population: 
[[1 1 0 0 1 0 1 0 0 1]
 [0 0 0 0 0 0 1 1 1 1]
 [1 1 1 1 1 0 1 1 1 0]
 [1 1 1 1 0 0 1 0 1 0]
 [1 0 0 1 1 0 1 0 1 0]
 [1 0 0 0 0 0 1 1 1 0]]


In [10]:
def cal_fitness(weight, priority_value, population, threshold):
    fitness = np.empty(population.shape[0])
    for i in range(population.shape[0]):
        S1 = np.sum(population[i] * priority_value)
        S2 = np.sum(population[i] * weight)
        if S2 <= threshold:
            fitness[i] = S1
        else :
            fitness[i] = 0 
    return fitness.astype(int) 

In [4]:
print('First fitness : \n{}\n'.format(cal_fitness(weight, priority_value, initial_population, max_item)))

First fitness : 
[180 190   0 300 240 230]



In [11]:
def selection(fitness, num_parents, population):
    fitness = list(fitness)
    parents = np.empty((num_parents, population.shape[1]))
    for i in range(num_parents):
        max_fitness_idx = np.where(fitness == np.max(fitness))
        parents[i,:] = population[max_fitness_idx[0][0], :]
        fitness[max_fitness_idx[0][0]] = -999999
    return parents

In [12]:
 
def crossover(parents, num_offsprings):
    offsprings = np.empty((num_offsprings, parents.shape[1]))
    crossover_point = int(parents.shape[1]/2)
    crossover_rate = pc_value
    i=0
    while (parents.shape[0] < num_offsprings):
        parent1_index = i%parents.shape[0]
        parent2_index = (i+1)%parents.shape[0]
        x = rd.random()
        if x > crossover_rate:
            continue
        parent1_index = i%parents.shape[0]
        parent2_index = (i+1)%parents.shape[0]
        offsprings[i,0:crossover_point] = parents[parent1_index,0:crossover_point]
        offsprings[i,crossover_point:] = parents[parent2_index,crossover_point:]
        i=+1
    return offsprings   

In [13]:
def mutation(offsprings):
    mutants = np.empty((offsprings.shape))
    mutation_rate = pm_value
    for i in range(mutants.shape[0]):
        random_value_priority = rd.random()
        mutants[i,:] = offsprings[i,:]
        if random_value_priority > mutation_rate:
            continue
        int_random_value_prioritas = randint(0,offsprings.shape[1]-1)    
        if mutants[i,int_random_value_prioritas] == 0 :
            mutants[i,int_random_value_prioritas] = 1
        else :
            mutants[i,int_random_value_prioritas] = 0
    return mutants

In [14]:
def optimize(weight, priority_value, population, pop_number, num_generations, threshold):
    parameters, fitness_history = [], []
    num_parents = int(pop_number[0]/2)
    num_offsprings = pop_number[0] - num_parents 
    for i in range(num_generations):
        fitness = cal_fitness(weight, priority_value, population, threshold)
        fitness_history.append(fitness)
        parents = selection(fitness, num_parents, population)
        offsprings = crossover(parents, num_offsprings)
        mutants = mutation(offsprings)
        population[0:parents.shape[0], :] = parents
        population[parents.shape[0]:, :] = mutants
        
    print('Last generation: \n{}\n'.format(population)) 
    fitness_last_gen = cal_fitness(weight, priority_value, population, threshold)      
    print('Fitness of the last generation: \n{}\n'.format(fitness_last_gen))
    max_fitness = np.where(fitness_last_gen == np.max(fitness_last_gen))
    parameters.append(population[max_fitness[0][0] ,:])
    return parameters, fitness_history

In [17]:
parameters, fitness_history = optimize(weight, priority_value, initial_population, pop_number, num_generations, max_item)
print('Theoptimized parameters for the given input are: \n{}'.format(parameters))
selected_items = item_number * parameters
print('\nItems to be brought and put in the bag ::')
for i in range(selected_items.shape[1]):
  if selected_items[0][i] != 0:
     print('{}\n'.format(selected_items[0][i]))


Last generation: 
[[1 0 1 1 1 1 1 0 1 0]
 [1 0 1 1 1 1 1 0 1 0]
 [1 0 1 1 1 1 1 0 1 0]
 [1 0 1 1 0 1 1 0 1 0]
 [1 0 1 1 1 1 1 0 1 0]
 [1 0 1 1 1 1 1 0 1 0]]

Fitness of the last generation: 
[430 430 430 380 430 430]

Theoptimized parameters for the given input are: 
[array([1, 0, 1, 1, 1, 1, 1, 0, 1, 0])]

Items to be brought and put in the bag ::
1

3

4

5

6

7

9

